export const ADD_STUDENT = 'ADD_STUDENT';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';

export const LOAD_STUDENTS_FROM_STORAGE = 'LOAD_STUDENTS_FROM_STORAGE';
